language: php
php:
  - 5.6
  - 5.5

before_script:
    - curl -s http://getcomposer.org/installer | php
    - composer install --prefer-source --no-interaction

script:
    - phpunit
    - phpunit --coverage-clover build/logs/clover.xml
    - CODECLIMATE_REPO_TOKEN=a43647d64b6bdb43b768271ab530be404d96ce65c37f9b0ab649a3d814371c8c ./vendor/bin/test-reporter
